# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
terminationGracePeriodSeconds: 30
image:
  repository: 923662548032.dkr.ecr.eu-west-1.amazonaws.com/lightninglabs/bitcoin-core
  tag: latest
  pullPolicy: IfNotPresent

service:
  rpcPort: 8332
  p2pPort: 8333
  testnetPort: 18332
  testnetP2pPort: 18333
  zmqpubrawblock: 28332
  zmqpubrawtx: 28333
  
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 300Gi

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources: 
  requests:
    memory: 1024Mi
    cpu: 1000m

# Custom bitcoind configuration file used to override default bitcoind settings
configurationFile:
  bitcoin.conf: |-
    testnet=1
    server=1
    printtoconsole=1
    txindex=1
    disablewallet=1
    [test]
    zmqpubrawblock=tcp://0.0.0.0:28332
    zmqpubrawtx=tcp://0.0.0.0:28333
    rpcport=18332
    rpcbind=0.0.0.0
    rpcallowip=::/0
    rpcuser=lightning
    rpcpassword=lightning
