apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bitcoind.fullname" . }}-bitcoin-core
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.bitcoind.configurationFile | indent 2 }}
