apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/bitcoin.conf /home/bitcoin/.bitcoin/bitcoin.conf']
          volumeMounts:
            - name: configmap-bitcoind
              mountPath: /configmap
            - name: bitcoind-config
              mountPath: /home/bitcoin/.bitcoin/
        - name: copy-lnd-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/lnd.conf /home/bitcoin/.lnd/lnd.conf']
          volumeMounts:
            - name: configmap-lnd
              mountPath: /configmap
            - name: lnd-config
              mountPath: /home/bitcoin/.lnd/
      
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.bitcoind.repository }}:{{ .Values.bitcoind.tag }}"
          imagePullPolicy: {{ .Values.bitcoind.pullPolicy | quote }}
          resources:
{{ toYaml .Values.bitcoind.resources | indent 12 }}
          ports:
            - name: bitcoindP2p
              containerPort: {{ .Values.bitcoind.service.p2pPort }}
          volumeMounts:
            - name: data
              mountPath: /home/bitcoin
            {{- if .Values.bitcoind.configurationFile }}
            - name: bitcoind-config
              mountPath: /home/bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
            
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.lnd.repository }}:{{ .Values.lnd.tag }}"
          imagePullPolicy: {{ .Values.lnd.pullPolicy | quote }}
          resources:
{{ toYaml .Values.lnd.resources | indent 12 }}
          ports:
            - name: lndP2p
              containerPort: {{ .Values.lnd.service.p2pPort }}
          volumeMounts:
            - name: data
              mountPath: /home/bitcoin
            {{- if .Values.lnd.configurationFile }}
            - name: lnd-config
              mountPath: /home/bitcoin/.lnd/lnd.conf
              subPath: lnd.conf
            {{- end }}

        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.lseed.repository }}:{{ .Values.lseed.tag }}"
          imagePullPolicy: {{ .Values.lseed.pullPolicy | quote }}
          # command: ["lseed"]
          # args: ["--listen", {{ .Values.lseed.args.listen }},
          # "--test-lnd-node", {{ .Values.lseed.args.testLndNode }},
          # "--test-tls-path", {{ .Values.lseed.args.tesTtlsPath }},
          # "--test-mac-path", {{ .Values.lseed.args.testMacPath }},
          # "--root-domain", {{ .Values.lseed.args.rootDomain }},
          # "--root-ip", {{ .Values.lseed.args.rootIP }},
          # "--poll-interval", {{ .Values.lseed.args.pollInterval }},
          # "--debug", {{ .Values.lseed.args.debug}},
          # "--results", {{ .Values.lseed.args.results }} ]
          
          resources:
{{ toYaml .Values.lseed.resources | indent 12 }}
          ports:
            - name: lseedPort
              containerPort: {{ .Values.lseed.service.lseedPort }}
          volumeMounts:
            - name: data
              mountPath: /home/bitcoin

            
      volumes:
        {{- if .Values.bitcoind.configurationFile }}
        - name: config
          emptyDir: {}
        - name: configmap-bitcoind
          configMap:
            name: {{ template "bitcoind.fullname" . }}-bitcoind
        {{- end }}
        {{- if .Values.lnd.configurationFile }}
        - name: config
          emptyDir: {}
        - name: configmap-lnd
          configMap:
            name: {{ template "bitcoind.fullname" . }}-lnd
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoind.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end -}}
