apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: bitcoin-core-p2p
      port: {{ .Values.bitcoin-core.service.p2pPort }}
    - name: lnd-p2p
      port: {{ .Values.bitcoin-core.service.p2pPort }}
    - name: lseedDNS
      port: {{ .Values.bitcoin-core.service.lseedDNS }}
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
