apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports: 
    - name: bitcoindP2p
      port: {{ .Values.bitcoind.service.p2pPort }}
    - name: lndP2p
      port: {{ .Values.lnd.service.p2pPort }}
    - name: lseedPort
      port: {{ .Values.lseed.service.lseedPort }}
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
